### ISSUE TITLE
Link job to transaction

### ISSUE THREAD

**Issue by jaimeiturriaga** [CSC444-FormalTigers/TeenServ#103]
Right now we just have it store the job id as service_id for the transactions model. The view for the model just shows the id for the job. This number isn't particularly useful for the user.

Instead, we should probably show the name of the job, and possibly link to the job. Problem though is when the job gets the deleted the user has no way of seeing the old job + description. Possible solution is to instead mark a job as archived instead of deleted, and the job is still viewable from the transactions.
Alternatively we just store the job name in the transaction model and show that in the view.

**Comment by YilongPan** [comment]
I have made job_name and hours_worked show on transaction history, also provided links to those jobs aren't destroyed.
