### ISSUE TITLE
Transaction model entry should only exist if payment completes

### ISSUE THREAD

**Issue by jaimeiturriaga** [CSC444-FormalTigers/TeenServ#104]
Right now the model entry is created as long as the api is valid. If the user decides to cancel the payment manually, the model entry is still there.
We should either create a model entry using the api returnUrl (this involves creating a new action for the transaction model, and having returnUrl redirect to that), or have the cancelUrl delete the model entry (again, this involves creating a destroy action for the transaction model).
The former however has flaws in it that the user has the ability to spoof their transactions.

**Comment by YilongPan** [comment]
Ok, I will try to make a destroy action for the transaction model. Also, jaimei, when I try to fill out the time-sheet form, I always get a authentication failure notice, does that mean my email address has to be registered on PayPal or something?

**Comment by jaimeiturriaga** [comment]
The person that you are paying needs a valid PayPal account. In particular a sandbox account.
The account I have setup for paypal is teenserv-worker@gmail.com

**Comment by YilongPan** [comment]
Ok, I see, thanks

**Comment by YilongPan** [comment]
Hi jaimei, I have made a destroy action, but wasn't able to test it. When i filled out the time sheet I still got an authentication error saying my credentials are invalid. I have put teenserv-worker@gmail.com as receiver's paypal email address, does employer need an sandbox account as well?

**Comment by jaimeiturriaga** [comment]
No, the employer doesn't need a paypal for this to work since the employer has to sign in to paypal to make the payment.
I just tested and it works for me, so I don't know what's causing the problem on your end.

**Comment by jaimeiturriaga** [comment]
Can you show me which user and job you are testing on using the live deploy? That way I can see what the problem is.
