### ISSUE TITLE
Update User model with useful info

### ISSUE THREAD

**Issue by hbsock** [CSC444-FormalTigers/TeenServ#12]
Currently User only have username/password/email.

Should specify:
- name (first, middle?, last)
- home address 
- Phone numbers (home & mobile)
- age
- profile picture

And these should also be added to the new user registration page.

Then each User model can own a Teenager/Client model for teenager or client specific information.

**Comment by bathalex210** [comment]
The model is mostly done already. The current user table is shown below, the only thing missing there is separate columns for names (first, middle, last). 
```
create_table "users", force: :cascade do |t|
    t.string "username"
    t.string "password"
    t.string "email"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "age"
    t.text "gender"
    t.text "cell_phone"
    t.text "home_phone"
    t.text "name"
    t.text "address"
    t.text "photo"
    t.text "account_type"
    t.string "password_digest"
end
```

As a side note, we planned on splitting the user groups into their own tables but the more I look at it the more I feel like it's too complicated. Currently, the only special thing that we have to store about any of the three user types is `resume` for `teenagers`. If everyone is fine with it, I think that just having one table `users` with all of the necessary columns would be easiest - you can just let resume be null for clients and admins. This would allow us to interact with only one table when dealing with user data storage and display. The final table would look like this:
```
create_table "users", force: :cascade do |t|
    t.string "username"
    t.string "password"
    t.string "email"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "age"
    t.text "gender"
    t.text "cell_phone"
    t.text "home_phone"
    t.text "first_name"
    t.text "middle_name"
    t.text "last_name"
    t.text "address"
    t.text "photo"
    t.text "account_type"
    t.string "password_digest"
    t.integer "rating"
    t.decimal "account_balance"
    t.text "bank_key"
    t.text "description"
    t.text "resume"
end
```

**Comment by hbsock** [comment]
Why would keeping separate tables be too complicated?

**Comment by bathalex210** [comment]
I explained above, feel free to do whatever you think is best.

**Comment by hbsock** [comment]
Alright, well let's just keep things simple as possible first. 

Let's keep everything in the User model if it will make things simpler.

**Comment by hbsock** [comment]
I'll beef up the registration page to include more information.
