### ISSUE TITLE
Make the website look beautiful with CSS.

### ISSUE THREAD

**Issue by hbsock** [CSC444-FormalTigers/TeenServ#15]

**Comment by bathalex210** [comment]
Added some basic styles. Things to note:

I used a CSS Reset code template to remove default browser CSS stylings. This means that some elements (p, h2, h3, h4) will all look the same until they are styled.

I added flash notifications and styled them blue for notice red for danger. Note they disappear after 5 seconds - that functionality is written in CSS in `style.css`.

Finally, I'm open to using bootstrap or any other tools if the team wants that.

**Comment by hbsock** [comment]
Holy you did a lot to make it beautiful, thanks Alex.

**Comment by bathalex210** [comment]
I put together some things for the front page, just a basic template really. Anyone should feel free to change it!
