### ISSUE TITLE
Only allow logged in users to access certain parts of the site.

### ISSUE THREAD

**Issue by hbsock** [CSC444-FormalTigers/TeenServ#21]
The welcome/login/registration pages should be open for anyone to view, but viewing jobs/users should be limited to people logged in.

Should redirect to login page if person not logged in attempts to go to a page that requires an existing session.

**Comment by jaimeiturriaga** [comment]
Did you guys want to implement this manually, or to use a gem like devise? If we use something like devise we won't have to worry about corner cases.

**Comment by bathalex210** [comment]
Looks like a solid option Jaime, saves us a lot of work

**Comment by hbsock** [comment]
Go for it Jaime.

**Comment by jaimeiturriaga** [comment]
Mostly implemented now. Just need to make sure users can't edit/delete other people's pages. Before this is done though we need to implement admin accounts that can edit/delete other people's pages.
