### ISSUE TITLE
Add/edit buttons on user index not getting clicked properly

### ISSUE THREAD

**Issue by hbsock** [CSC444-FormalTigers/TeenServ#40]
Problem occured at UG lab computers.

Occured on Firefox ESR 52.4.0 (64-bit).

**Comment by bathalex210** [comment]
Working on this now...

Was because I put the link inside a button element.

https://stackoverflow.com/questions/17253410/link-inside-a-button-not-working-in-firefox

**Comment by bathalex210** [comment]
Pushed a fix. Should be working on any browser now.
