### ISSUE TITLE
Filter out or sort jobs by area

### ISSUE THREAD

**Issue by jaimeiturriaga** [CSC444-FormalTigers/TeenServ#62]
Teenager only needs to know about local jobs. 
Here's a good api that helps with this.
https://developers.google.com/maps/documentation/distance-matrix/intro
Here's a wrapper for the google maps api
https://github.com/edwardsamuel/google-maps-services-ruby

**Comment by jaimeiturriaga** [comment]
I'm working on this now. I'm also updating our search method to use elasticsearch instead.

**Comment by jaimeiturriaga** [comment]
So to install any of the elasticsearch add-ons on heroku requires that the owner of the heroku app be verified. I.e. credit card information. Even if a plan is free, if there are any plans for that add-on that cost money, you still need to provide credit card information.

**Comment by hbsock** [comment]
@jaimeiturriaga I'll try to do this by using google maps. Will try to only list jobs around a location that is input by the user.

**Comment by hbsock** [comment]
I've added a search bar on job index so when it's input with a location, the map will automatically bound itself to seeing jobs within 5km of that input.

I'll figure out how to make the distance 5km configurable later.
