### ISSUE TITLE
Integrate google maps to display jobs on map.

### ISSUE THREAD

**Issue by hbsock** [CSC444-FormalTigers/TeenServ#66]
- [x] Add google maps to site
- [x] Add address to jobs
- [x] Display jobs at address on the map

**Comment by bathalex210** [comment]
I got a bit carried away and did some of this myself, sorry!

There is currently a bug with gmaps imports doubling up as you traverse around the site, I'm pretty sure it's because we're importing the maps api javascript inside a view but still investigating.

**Comment by bathalex210** [comment]
Found the bug, Turbolinks was loading each page with ajax and keeping the header in tact - each page with the maps api pinned a new import onto the head. I've disabled turbolinks until we compile all maps JS into one source file.

**Comment by hbsock** [comment]
Simply displaying jobs have been implemented.
