### ISSUE TITLE
Notification and edit_job buttons are overlapping on job show page.

### ISSUE THREAD

**Issue by hbsock** [CSC444-FormalTigers/TeenServ#70]
A screen shot of the issue. I have no clue how to move the button to the top left (I tried on css and failed miserably.)

![screenshot from 2017-11-19 12-16-35](https://user-images.githubusercontent.com/5956560/32993293-05f888c6-cd24-11e7-970f-be5040b17604.png)

**Comment by hbsock** [comment]
@bathalex210 could you help in fixing this?

**Comment by bathalex210** [comment]
Sure thing! on it

**Comment by bathalex210** [comment]
Adjusted z-index of notifications so that they will always be on top of other elements.
