### ISSUE TITLE
Should we worry about the specifications in project outline?

### ISSUE THREAD

**Issue by Danielhuxc** [CSC444-FormalTigers/TeenServ#73]
In particular:

Teenagers (aged 13-19, inclusive) register on the site and **specify the services they are willing to perform and at what price**. The TeenServ application you will create should **automatically connect clients and teenagers if there is a good match**. A **key requirement for your service is that the distance for the teenager to get from his/her house to the client be limited** (say to 1km or so, perhaps depending on the age of the teenager).

What do you guys think?

**Comment by hbsock** [comment]
Aw shit. It has to automatically connect clients and teens?

**Comment by Danielhuxc** [comment]
No more worries. Later in the document says it's up to us.
