### ISSUE TITLE
Teenagers should be able to list services they offer

### ISSUE THREAD

**Issue by jaimeiturriaga** [CSC444-FormalTigers/TeenServ#75]
We should add a new relation for types of services. Each user can than have many services, and each job can have one service. We can either define a list of services or users can create a new type of service either in their profile or when making a new job.

**Comment by hbsock** [comment]
I disagree.

I'm fine with tagging jobs with services, but teenagers shouldn't have to add anything to their profiles.
If they want to find babysitting jobs, they should be able to set a filter on the job index page to list jobs only with the babysitting tag.

Don't bother adding any new relations for this, just add a list of tags to the Job model that can be searchable.

**Comment by jaimeiturriaga** [comment]
Right now I'm adding all the stuff under "The TeenServ website should" from the project description. One of the points was to show the services a teenager is offering in their profile.

**Comment by hbsock** [comment]
The requirements for teens showing what services they can do doesn't make sense with our website's design.

Our website is employer based. The employer posts jobs, and teens figure out what they want. It doesn't make sense for teens to show what services they can do because our employers can't choose which teens are going to apply to their jobs.

These requirements are more flexible than what they seem. See: https://piazza.com/class/j7f1m2o672b5ft?cid=35

**Comment by jaimeiturriaga** [comment]
I'm confused, because in the instructor reply he says that the nature of project requirements is that they are required, not flexible.

**Comment by hbsock** [comment]
TA was referring to the requirements in general, for example the types of users HAVE to be admin, super admin, general public, teen, employer, sales representative.

But for the section on matching service it only gives EXAMPLES of how it could be implemented:
```
For example, a client can post a service they need with attendant details, and teenagers periodically review these posts, responding to those they wish to provide; that is, the teenagers are responsible for 
the matching. Alternatively, teenagers post services they offer along with the times they are 
available for the service, and clients select the teenager they wish to hire; that is, the clients are 
responsible for the matching
```

We're completely free to design how a teenager and employer are matched together.

**Comment by jaimeiturriaga** [comment]
If that's the case then so be it, although I still think we should have a separate model for the different types of services. If we end up with 10 static services, then those 10 services have to be hard coded into everything. Validations need to check that it is one of the 10 services, the job creation form needs to list all 10 services. If we create a model made of those services, than the validations and job creation forms just need to refer to that model. And in the case that we ever need to add more services, rather than having to modify the validations and the job creation form, we just modify the one model.

**Comment by hbsock** [comment]
The services can be an array of hard coded strings.

In pseudo code I visualize it as:

```rb
g__services = ["babysitting", "lawnmowing", "etc"]

class User < THINGY
  validate type_of_service,
    is_inside g__services
end
```

For the actual input by users, we can have the hardcoded array be used to list the options of a dropdown menu like how account_type is currently selected.

```
