### ISSUE TITLE
Automatically match clients with teenagers depending on services.

### ISSUE THREAD

**Issue by jaimeiturriaga** [CSC444-FormalTigers/TeenServ#76]
Couple of ways we can do this. For teenagers, we can filter out the jobs view to only include jobs for services they have on their profile. For clients, list all teenagers with this particular service and within range.

**Comment by hbsock** [comment]
I talked with the prof, we don't have to do anything "automatically".

We can add filtering as an option on the job index page, don't base it off of profile settings.

So have a filter button on job index and have fields like types of service, length, etc and filter the index of jobs with that form.
