### ISSUE TITLE
Search button on job index page doesn't even work

### ISSUE THREAD

**Issue by hbsock** [CSC444-FormalTigers/TeenServ#82]
@YilongPan I don't know any SQL, so I'm not sure how you've implemented the search function but it doesn't work.

when I have two jobs called "test" and "testan"
and try to search "testan", there are no results.

**Comment by jaimeiturriaga** [comment]
The search function just checks to see if a description contains the string.
It's going to be nearly impossible to implement a competent searching algorithm, considering that there are entire programs dedicated to searching. There are heroku add-ons that allow you to have a searching server for free (under a certain amount of queries), however the owner of the heroku app needs to have their credit card registered before you can install the add-on.

**Comment by hbsock** [comment]
Then how about we just get rid of searching, and replace it with filtering?

Who cares about the specific titles or descriptions, just filter for specific dates, wages, etc.

**Comment by jaimeiturriaga** [comment]
I was actually planning on reworking the search to do tag searches instead, although having a set of checkboxes would be less cumbersome.

**Comment by hbsock** [comment]
Let's do set of check boxes. Screw tags, tags are too complicated.

**Comment by hbsock** [comment]
@jaimeiturriaga since you've added the job type searching, can you remove the old search bar and the part of the search function in the Job model that used the search?

Don't also forget to remove the argument that contained the search bar!

**Comment by jaimeiturriaga** [comment]
I thought you were planning on using the search function to filter out job areas by location. As in the user types in a location and it filters depending on distance from location.

**Comment by hbsock** [comment]
Oh, I wasn't going to use the search method on the JobController. I was planning on directly getting the search param to the javascript function for searching on googlemaps.

**Comment by jaimeiturriaga** [comment]
Alright, I'll modify the search method and remove the search bar. I'll keep the search method however, as it's more convenient to keep the if statement there as I just need to chain off of whatever gets returned by the search method.

**Comment by hbsock** [comment]
I suggest if you want to filter the results from google map, send the filtering parameters into the javascript.

As in: convert the filtering params to JSON array and use that in the google maps searching. That'd be more convenient I think. In fact, I can implement that if you want.

**Comment by jaimeiturriaga** [comment]
I need to learn how the google maps does the searching anyway, so I'll do it.
