### ISSUE TITLE
Timesheets,Billing,Transactions,and Payments

### ISSUE THREAD

**Issue by Danielhuxc** [CSC444-FormalTigers/TeenServ#90]
After a teenager has performed a service, the teenager must complete some form of a 
timesheet to indicated how long s/he worked and for which client. The client must then accept 
the timesheet. When this has occurred, then:
1. a transaction is created in a database that identifies
• the teenager
• the client
• the type of work performed
• when the work was performed
• how many hours it involved
• the hourly rate
• the total amount
2. client is billed the total amount plus service fees, and their credit card is charged.
3. the teenager is credited with the total amount
Each client and each teenager should have access to the entire history of all their transactions. 
Credit card transactions that do not go through should be handled properly. Teenagers are not 
necessarily payed after each transaction; they have something like an account with TeenServ, 
but may request payment at any time. You will not be able to deposit money into a teenagers 
credit card account, but instead either must do a direct deposit into their bank account, send 
them an e-payment, or send them a check they can deposit somewhere.3
Your application should also be able to keep track of its own financials; i.e., how much money it 
has made each month.
One of the key design decisions you will have to make is how much teenagers are allowed to 
charge. There are a number of options with different tradeoffs, including:
• TeenServ sets the hourly rate for each service (perhaps depending on the age of the 
teenager4
).
• Each teenager gets to set their hourly rate for each service.5
• Clients get to select the hourly rate they are willing to pay for a specific service they are 
looking for.6
Which option is chosen may affect the matching scheme used.

**Comment by Danielhuxc** [comment]
Flow:

- [ ] add _hours_worked: integer_ to _JobApplication_ table
- [ ] add _balance: float_ to _User_ table
- [ ] 1. Teenager sets _job_application.hours_worked_ after finish job, display (payment request sent) if _hours_worked_ is set
- [ ] 2. Client Job show page display confirmation request if _hours_worked_ is set for accepted application
- [ ] 3 option a. Client refuses, clear hours_worked 
- [ ] 3 option b. Client accept, proceed with **payment** 
- [ ] 4. Payment received. Create transaction for later review.
- [ ] 5. Delete Application. Delete job as well if job is not reoccurring
- [ ] 6. balance in teenager profile is updated
- [ ] 7. teenager can **withdraw** fund
- [ ] 8. Show related transaction in user profile

**Comment by jaimeiturriaga** [comment]
We don't hold any funds for the teenager. Payment goes straight to them via PayPal.

**Comment by Danielhuxc** [comment]
Jaime suggested that current implementation is better, issue closed.
