### ISSUE TITLE
Job show does not properly allow user to apply.

### ISSUE THREAD

**Issue by jaimeiturriaga** [CSC444-FormalTigers/TeenServ#95]
Right now, the job's show page doesn't know when to show the "apply to job" option or not. If the user has applied to one other job, they cannot apply to any other jobs.
This is because the way we are testing if a user has applied to a job is by using some job_application attributes. However the only attributes set in job_application are is_accepted, and the associations. The code for this needs to be changed by checking through associations rather than through the attribute.

**Comment by jaimeiturriaga** [comment]
Nvm, the problem was with the improperly formatted where.
I do have a new problem though. User can't delete their application. It gives the error (resource not found).

**Comment by hbsock** [comment]
Try deleting your old users and jobs and create new users.

I think it's because I didn't update the old database when I was doing migrations to add relations. So old users/jobs may have errors.

**Comment by jaimeiturriaga** [comment]
These are with completely brand new users and jobs.

**Comment by jaimeiturriaga** [comment]
I'm going to push my fix for being unable to apply to multiple jobs, and see if the problem shows up in live.

**Comment by jaimeiturriaga** [comment]
nvm I fixed the problem.
