### ISSUE TITLE
Remove Ability to change account type from edit page

### ISSUE THREAD

**Issue by jaimeiturriaga** [CSC444-FormalTigers/TeenServ#99]
I'm thinking that we should keep the user from being able to edit their account type. There are only really special cases where a user needs to change their account type (due to error during sign up as an example). As such I think they should only be able to change it by contacting support (an admin) to change it for them.

Any thoughts on this?

**Comment by hbsock** [comment]
Okay. To implement can't you just change the user_params to:

```rb
    def user_params
       permitted_params = [:username,
        :password,
        :password_confirmation,
        :email,
        :name,
        :age,
        :gender,
        :cell_phone,
        :home_phone,
        :address,
        :photo,
        :avatar,
        :resume]

      permitted_params << :account_type if current_user.is_admin?

      params.require(:user).permit(permitted_params)
    end 

```

And of course change the views accordingly as well.

**Comment by jaimeiturriaga** [comment]
Okay, I phrased the question poorly.
What I meant to say is, is everyone all right with this decision?

**Comment by hbsock** [comment]
I'm fine with it.

**Comment by Character24** [comment]
Go for it. I originally made any user to edit because at the time, existing users needed to be assigned as an employer or teenager.
